### ISSUE TITLE
Certificate ARN changes after validarion

### ISSUE THREAD

**Issue by pancochea** [operatehappy/terraform-aws-acm-certificate#10]
# Expected Behavior

The arn output value should contain the valid ARN for the certificate.

## Current Behavior

When attaching to a cloudfront distribution (not sure if happens the same with ALBs or other resources), the certificate arn is passed to the distribution creation before it's valid. 

Looks like the ARN changes after the validation, and the linked distribution fails stating that the certificate does not exists in the virginia zone.

Re-running the run works as the certificate correct arn is passed

## Steps to Reproduce

Create a certificate using the module
Create a Cloudfornt distribution linked to the module's arn output variable

We solved the issue by changing the output to 
```hcl
output "arn" {
  value       = aws_acm_certificate_validation.this.certificate_arn
  description = "ARN of the Certificate"
  depends_on = [
    aws_acm_certificate_validation.this
  ]
}
```
## Environment

1.) Output of `terraform version` incl. provider(s):

```sh
terraform v0.15
```

2.) Version of the module: ``

3.) Any other relevant environment information:

```sh

```

**Comment by ksatirli** [comment]
Hey @pancochea I'm unable to reproduce this at this point on Terraform 1.3.x
